### ISSUE TITLE
Integration with pyrokinetics

### ISSUE THREAD

**Issue by bpatel2107** [rahulgaur104/ideal-ballooning-solver#1]
I think this could couple very nicely to pyrokinetics https://github.com/pyro-kinetics/pyrokinetics

Pyro should be able calculate all the inputs for this (I believe it essentially does). I would be be happy to call this as a library but if we could integrate the code directly into pyrokinetics then it could become more powerful. Either way it would allow for interfacing with a lot of different sources of data and would also make pyro a more powerful tool.

**Comment by rahulgaur104** [comment]
Hi Bhavin,

Good to see that Pyro is getting traction! Every local gyrokinetic solver has all the geometric coefficients needed to run this solver. In fact, my geometry module (that Liam worked on and is a part of this code) essentially calculates the coefficients for a gyrokinetic solver. Feel free to integrate this code into pyrokinetics. I may end up converting it into a package in the future, but I want other researchers to use this solver right now.

Rahul

**Comment by rahulgaur104** [comment]
Closing this since you have successfully added this solver to pyro.
